### ISSUE TITLE
用語リンク表示にカスタマイズ用class属性

### ISSUE THREAD

**Issue by shimizukawa** [yyyk-bp/redmine_glossary#6]
用語のリンクが多すぎると読みづらくなるため、cssでカスタマイズしたい。
そのために用語リンクにclassを設定して欲しい。

**Comment by yyyk-bp** [comment]
redmineってカスタムのcssみたいの設定できるんでしたっけ？

つまり {{term(term)}} から生成される aタグに `class="glossary-term"` とかつければ目的は達成される？

**Comment by shimizukawa** [comment]
はい

**Comment by yyyk-bp** [comment]
ry

**Comment by yyyk-bp** [comment]
対応済み
