### ISSUE TITLE
Redmineの検索ボックスで用語集も検索対象にしてほしい

### ISSUE THREAD

**Issue by shimizukawa** [yyyk-bp/redmine_glossary#8]
Redmine本体の検索機能では、「チケット」「Wiki」「ニュース」が検索できます。用語集も検索対象にして欲しいです。

**Comment by yyyk-bp** [comment]
調べてみないとわかりませんが、検索のプラグインをつくらないと無理なんじゃないですかね。。。

**Comment by yyyk-bp** [comment]
init.rb で `Redmine::Search.register :Term` の1行加えて Term class に `acts_as_searchable` っていうオプションをなんやかんやするとできそうだけど現状エラーがでてしまう

- ドキュメントがない（ほしい）
- 別の問題として権限まわりの設定がちゃんとされてない気がする

**Comment by yyyk-bp** [comment]
> エラー

`acts_as_attachable` を間違って触っていた。解決。

> プラグイン開発のドキュメントがない（ほしい）

- https://www.amazon.co.jp/Redmine-Plugin-Extension-Development-Bevilacqua-ebook/dp/B00J4LO3Q8 

> プロジェクトが選択されている状態とされていない状態で検索するページの種類(wiki, チケットなど)に入ったり入らなかったりするのがよくわからない

x: `Redmine::Search.register :Term`, o: `Redmine::Search.register :terms` 

ここから `view_terms` 権限をみて、権限があれば表示される

**Comment by yyyk-bp** [comment]
対応済み
